
import { StandardTableView } from "std-widgets.slint";
import { TableData ,  Relative} from "../types.slint";
export component Table inherits StandardTableView {
    callback show-popup-window();
    in property <[[StandardListViewItem]]> data;
    in-out property <[TableColumn]> c: [
        { title: "id", width: 50px },
        { title: "Pinned", width: 80px },
        { title: "Name" },
        { title: "Age", width: 70px },
        { title: "Sameness", width: 100px },
        { title: "Mother" },
        { title: "Father" },
        { title: "Phone" },
        { title: "Email" },
        { title: "Lost Reason" },
        { title: "state", width: 80px },
    ];

    current-row-changed => {
        TableData.current_row = self.current-row;
        TableData.active-tab = 1;
        TableData.has_selected_row = true;
        TableData.current-row-changed(TableData.current_row);
        show_popup_window();
    }
    columns: c;
    rows: data;
}

export component FemalesTable inherits StandardTableView {
    callback show-popup-window();
    in property <[[StandardListViewItem]]> data;
    in-out property <[TableColumn]> c: [
        { title: "id", width: 50px },
        { title: "Pinned", width: 80px },
        { title: "Name" },
        { title: "Age" },
        { title: "Sameness" },
        { title: "Phone" },
        { title: "Email" },
        { title: "hotness" },
        { title: "swarthy" },
        { title: "crazy" },
        { title: "Lost Reason" },
        { title: "state", width: 80px },
    ];

    current-row-changed => {
        TableData.current_row = self.current-row;
        TableData.has_selected_row = true;
        TableData.active-tab = 2;
        TableData.current-row-changed(TableData.current_row);
        show_popup_window();
    }
    columns: c;
    rows: data;
}

export component EmployeesTable inherits StandardTableView {
    callback show-popup-window();
    in property <[[StandardListViewItem]]> data;
    in-out property <[TableColumn]> c: [
        { title: "id", width: 50px },
        { title: "Pinned", width: 80px },
        { title: "Name" },
        { title: "Age" },
        { title: "Sameness" },
        { title: "Phone" },
        { title: "Email" },
        { title: "employable" },
        { title: "Lost Reason" },
        { title: "state", width: 80px },
    ];

    current-row-changed => {
        TableData.current_row = self.current-row;
        TableData.has_selected_row = true;
        TableData.active-tab = 3;
        TableData.current-row-changed(TableData.current_row);
        show_popup_window();
    }
    columns: c;
    rows: data;
}
