
export enum Command { PIN, UNPIN}

export struct Relative {
    id: string,
    first-name: string,
    middle-name: string,
    last-name: string,
    sex: string,
    age: int,
    phone: string,
    email: string,
    pinned: bool,
    birthday: string,
    address: string,
    state: string,
    deathday: string,
    lost-reason: string,
    sameness: string,
    note: string,
    hotness: int,
    swarthy: int,
    crazy:int,
    employable: int,
    mother_id: int,
    father_id: int,
    created_at: string,
    updated_at: string,
  }

export struct Note {
  id: string,
  relative_id: string,
  pinned: bool,
  text: string,
}

/*export struct File {
  id: string,
  imported_name: string,
  imported_hash: string,
  relative_id: string,
  type: string,
  size: string,
  filename: string,
  pinned: string,
    
}*/

export struct File {
  id: string,
  relative_id: string,
  type: string,
  filename: string,
  pinned: bool,
    
}
export enum ActiveTab{relative, employees, females}


export global TableData {
    in property <[[StandardListViewItem]]> relative;
    in property <[[StandardListViewItem]]> females;
    in property <[[StandardListViewItem]]> employees;
    in property <[string]> males;
    in property <[string]> females2;
    in-out property <string> selected-mother-name;
    in-out property <string> selected-father-name;
    in-out property <int> current_row;
    in-out property <bool> has_selected_row;
    in-out property <int> active-tab;
    callback current-row-changed(int);
    in-out property <Relative> active-relative;
    in-out property <image> active-profile-image;
    callback add-image-for-relative(string);
    in-out property <[[StandardListViewItem]]> notes-rows-for-active-relative;
    in-out property <[[StandardListViewItem]]> files-rows-for-active-relative;
    in-out property <[[StandardListViewItem]]> images-rows-for-active-relative;
    in-out property <Note> active-note;
    in-out property <bool> has-active-note;
    in-out property <int> current-notes-row;
    in-out property <File> active-file;
    in-out property <bool> has-active-file;
    in-out property <int> current-files-row;
    in-out property <int> current-image-row;
    in-out property <bool> has-active-image;
    callback pin-active-note(string, Command);
    callback pin-active-file(string, Command); // first string is for id, second is for command. "PIN" or UNPIN
    callback delete-active-note(string); // the string is for id ( for validation)
    callback delete-active-file(string); // the string id for id (for validation)
    callback save-edited-note(string, string); // first string is id second it the note to save.
    callback current-note-row-change(int);
    callback current-file-row-change(int);
    callback current-image-row-change(int);
    callback delete-current-image(int);
    in-out property <Relative> new-relative;
    in-out property <string> active-relative-image;
    callback close-request();
    callback create-new-relative(Relative, string, string); // first string is mother name, second is father name
    callback update-relative(string, Relative, string, string); // first parameter is an id used to track the relative. third is mother, fourth is father
    callback delete-relative(string);
    in-out property <string> error;
    in-out property <string> success-msg;
    in-out property <string> image-error;
    in-out property <string> files_error;
    in-out property <string> notes-error;
    callback add-files-for-relative(int, string);
    callback add-note-for-relative(string, string); // first parameter is id. second in the actual note text
    in-out property <[string]> selected-relative-files;
    in-out property <[string]> selected-relative-notes;
    callback show-update-window();
    callback show-add-window();
    in-out property <string> create-success;
    in-out property <string> create-error;
    in-out property <string> update-success;
    in-out property <string> update-eror;
    in-out property <image> check-image;
    in-out property <image> cross-image;
    in-out property <image> temporary-image;
    callback chose-temporary-image();
    in-out property <string> temporary-image-path;
}

export global CrudMessages {
    in-out property <string> upload-image-error;
    in-out property <string> upload-image-success;
    in-out property <string> edit-note-error;
    in-out property <string> pin-note-error;
    in-out property <string> delete-relative-error;
    in-out property <string> delete-relative-success;
}
