import { Button } from "std-widgets.slint";
export component CustomButton inherits Rectangle {
    in property <string> title;
    in property <brush> background-color;
    callback clicked <=> touch.clicked;
    border-radius: 5px;
    background: background-color;
    t := Text {
        text: title;
        color: #fff;
    }

    touch := TouchArea {
        width: 100%;
        height: 100%;
    }
}
