import { CustomButton } from "button.slint";
export component DeleteComfirm inherits PopupWindow {
    callback clicked();
    close-on-click: false;
    height: 250px;
    width: 400px;
    Rectangle {
        height: parent.height;
        width: parent.width;
        background: #ffffff;
        border-radius: 8px;
        drop-shadow-color: #00000029;
        drop-shadow-offset-x: 0px;
        drop-shadow-offset-y: 4px;
        drop-shadow-blur: 24px;
        VerticalLayout {
            padding: 20px;
            spacing: 24px;
            alignment: space-between;
            Text {
                text: @tr("Confirm Delete, This Action is irreversible");
                font-size: 18px;
                font-weight: 500;
                horizontal-alignment: center;
                wrap: word-wrap;
                color: #111827;
            }

            HorizontalLayout {
                spacing: 12px;
                alignment: end;
                CustomButton {
                    width: 100px;
                    height: 36px;
                    title: "Cancel";
                    background: #f3f4f6;
                    text-color: #374151;
                    border-radius: 6px;
                    clicked => {
                        root.close();
                    }
                }

                CustomButton {
                    width: 100px;
                    height: 36px;
                    title: "Delete";
                    background: #ef4444;
                    text-color: #ffffff;
                    border-radius: 6px;
                    clicked => {
                        root.clicked();
                    }
                }
            }
        }
    }
}
