
import { CustomButton } from "button.slint";
export component MessagePopup inherits PopupWindow {
    in-out property <string> message-on-success;
    in-out property <string> message-on-error;
    in-out property <length> x-pos;
    in-out property <length> y-pos;
    height: 200px;
    width: 400px;
    close-on-click: false;
    x: x-pos;
    y: y-pos;

    Rectangle {
        width: parent.width;
        height: parent.height;
        background: #ffffff;
        border-radius: 12px;
        drop-shadow-color: #00000020;
        drop-shadow-offset-x: 0px;
        drop-shadow-offset-y: 4px;
        drop-shadow-blur: 16px;

        VerticalLayout {
            padding: 24px;
            spacing: 20px;

            Rectangle {
                height: 160px;
                width: 320px;
                border-radius: 24px;
                background: message-on-success != "" ? #E7F7EE : #FEE4E2;

                Image {
                    source: message-on-success != "" ? @image-url("../../assets/icons/check-circle.svg") : @image-url("../../assets/icons/x-circle.svg");
                    width: 24px;
                    height: 24px;
                    x: (parent.width - self.width) / 2;
                    y: (parent.height - self.height) / 2;
                    colorize: message-on-success != "" ? #039855 : #D92D20;
                }
            }

            Text {
                horizontal-alignment: center;
                text: message-on-success != "" ? message-on-success : message-on-error;
                font-size: 16px;
                font-weight: 500;
                wrap: TextWrap.word-wrap;
                color: #101828;
            }

            HorizontalLayout {
                alignment: center;
                padding-top: 8px;

                CustomButton {
                    width: 80px;
                    height: 30px;
                    background: message-on-success != "" ? #039855 : #D92D20;
                    border-radius: 8px;
                    title: "Close";
                    text-color: white;

                    clicked => {
                        message-on-success = "";
                        message-on-error = "";
                        root.close()
                    }
                }
            }
        }
    }
}
