
import { StandardTableView } from "std-widgets.slint";
import { TableData } from "../types.slint";
import { Relative } from "../types.slint";
export component Table inherits StandardTableView {
    callback show-popup-window();
    in property <[[StandardListViewItem]]> data;
    in-out property <[TableColumn]> c:
    
  [
        { title: "Name" },
        { title: "Age" },
        { title: "Sameness" },
        { title: "Mother" },
        { title: "Father" },
        { title: "Phone" },
        { title: "Email" },
        { title: "Pinned" },
        { title: "Lost Reason" },
        { title: "Created" },
        { title: "Updated" }
    ];
    current-row-changed => {
        TableData.current_row = self.current-row;
        TableData.current-row-changed(self.current-row);
        TableData.has_selected_row = true;
        show_popup_window();
    }
    columns: c;
    rows: data;
}
