
import { CustomButton } from "button.slint";
import { TableData } from "../types.slint";
import { Palette } from "std-widgets.slint";

export component TaskBar inherits Rectangle {
    callback close-popup();
    in-out property <LayoutAlignment> alignment;
    in-out property <length> h;
    in-out property <color> color-light;
    in-out property <color> color-dark;
    height: h;
    background: Palette.color-scheme == ColorScheme.dark ? color-dark : color-light;
    HorizontalLayout {
        alignment: alignment; /*
        CustomButton {
            title: "Close";
            height: parent.height - 10px;
            clicked => {
                // reset
                TableData.error = "";
                TableData.selected-father-id = -1;
                TableData.selected-mother-id = -1;
                TableData.notes-error = "";
                TableData.files_error = "";
                TableData.image-error = "";
                close-popup()
            }
        }

        Text {
            text: TableData.error;
            color: Colors.red;
        }
    */
        @children
    }
}
