  
import { CustomButton } from "../components/button.slint";
import { Button, CheckBox, Switch, HorizontalBox, LineEdit, GroupBox, ComboBox, DatePickerPopup, VerticalBox, Palette, StandardTableView } from "std-widgets.slint";
import { TableData } from "../types.slint";
export component Header inherits Rectangle {
    in-out property <bool> dark-mode;
    y: 5px;
    preferred-width: 100%;
    height: 50px;

    HorizontalLayout {
        alignment: space-between;
        Rectangle {
            border-radius: 5px;
            width: parent.width / 2;
            Text {
                text: "Add / Update";
                font-size: 18px;
            }
        }

        Rectangle {
            border-radius: 5px;
            width: parent.width / 2;
            HorizontalLayout {
                alignment: end;
                Button {
                    text: "Settings";
                }

                Button {
                    text: "About";
                }

                Switch {
                    text: @tr("Dark Mode {}", TableData.current_row);
                    checked: Palette.color-scheme == ColorScheme.dark;
                    toggled => {
                        Palette.color-scheme = self.checked ? ColorScheme.dark : ColorScheme.light;
                    }
                }
            }
        }
    }
}

export component AddUpdateView inherits Rectangle {
    min-width: 400px;
    preferred-height: 100%;
    preferred-width: 100%;

    Header { }

    Rectangle {

        y: 60px;
        preferred-width: 100%;

        VerticalLayout {
            Rectangle {
                GroupBox {
                    x: 0;
                    y: 0;
                    HorizontalLayout {
                        alignment: space-between;
                        VerticalLayout {
                            spacing: 10px;
                            HorizontalBox {
                                alignment: start;
                                padding: 0px;
                                LineEdit {
                                    height: 30px;
                                    placeholder-text: "Fist Name";
                                }

                                LineEdit {
                                    height: 30px;
                                    placeholder-text: "Middle Name";
                                }

                                LineEdit {
                                    height: 30px;
                                    placeholder-text: "Last Name";
                                }
                            }

                            HorizontalBox {
                                alignment: start;
                                padding: 0px;
                                ComboBox {
                                    model: [@tr("Select Sex"), @tr("Male"), @tr("Female"), @tr("Other")];
                                }

                                Button {
                                    text: @tr("Bithday");
                                    clicked => {
                                        birthday-picker.show();
                                    }
                                }

                                Button {
                                    text: @tr("Died");
                                    clicked => {
                                        died-picker.show();
                                    }
                                }

                                Rectangle {
                                    height: 20px;
                                    width: 30px;
                                    Text {
                                        text: "age";
                                    }
                                }
                            }
                        }

                        VerticalBox {

                            alignment: end;
                            Rectangle {
                                height: 300px;
                                width: 300px;
                                border-radius: 10px;
                                Text {
                                    text: "Image";
                                }

                                background: Palette.color-scheme == ColorScheme.dark ? #3b4252 : #d8dee9;
                            }

                            CustomButton {
                                title: "Upload Photo";
                                height: 30px;
                                background: Palette.color-scheme == ColorScheme.dark ? #3b4252 : #d8dee9;
                            }
                        }
                    }
                }
            }

            Rectangle {
                buttonsA := HorizontalLayout {
                    x: 0;
                    y: 0;
                    height: 50px;
                    spacing: 10px;
                    alignment: space-around;
                    Button {
                        height: 30px;
                        text: @tr("Add Mother");
                    }

                    Button {
                        height: 30px;
                        text: @tr("Add Father");
                    }
                }

                tables := HorizontalLayout {
                    x: 0;
                    y: buttonsA.height;
                    height: 350px;
                    Rectangle {
                        StandardTableView {
                            y: 0;
                            x: 20px;
                            columns: [{ title: "Name" }, { title: "Born" }];
                            rows: [
                                [{ text:"Sister Hotty" }, { text: "4-5-2023" }],
                                [{ text: "Brother Bob Thorton" }, { text: "6-3-2024" }],
                                [{ text: "Sister Hunter" }, { text: "9-1-2024" }],
                                [{ text: "Brother Lewis" }, { text: "8-15-2024" }],
                                [{ text: "Brother Eastwood" }, { text: "12-31-2023" }],
                            ];
                        }
                    }

                    Rectangle {
                        StandardTableView {
                            y: 0;
                            x: 20px;
                            columns: [{ title: "Name" }, { title: "Born" }];
                            rows: [
                                [{ text:"Henrietta Hotty" }, { text: "4-5-2023" }],
                                [{ text: "Billy Bob Thorton" }, { text: "6-3-2024" }],
                                [{ text: "Holly Hunter" }, { text: "9-1-2024" }],
                                [{ text: "Julliete Lewis" }, { text: "8-15-2024" }],
                                [{ text: "Clint Eastwood" }, { text: "12-31-2023" }],
                            ];
                        }
                    }
                }

                HorizontalLayout {
                    x: 0;
                    y: tables.height;
                    Rectangle {
                        HorizontalLayout {
                            x: 0;
                            y: 0;
                            height: 50px;
                            spacing: 10px;
                            alignment: space-around;
                            Button {
                                height: 30px;
                                text: @tr("Add Child");
                            }

                            Button {
                                height: 30px;
                                text: @tr("Add Sibling");
                            }

                            Button {
                                height: 30px;
                                text: @tr("Pin/Unpin record");
                            }

                            Button {
                                height: 30px;
                                text: @tr("Save Record");
                            }

                            CustomButton {
                                padding: 10px;
                                height: 30px;
                                width: 100px;
                                title: @tr("Delete Record");
                                background: blue;
                            }
                        }
                    }
                }
            }
        }
    }

    birthday-picker := DatePickerPopup {
        x: (root.width - self.width) / 2;
        y: (root.height - self.height) / 2;
    }

    died-picker := DatePickerPopup {
        x: (root.width - self.width) / 2;
        y: (root.height - self.height) / 2;
    }
}
