import { CustomButton } from "../components/button.slint";
import { Button, CheckBox, Switch, HorizontalBox, LineEdit, GroupBox, ComboBox, DatePickerPopup, VerticalBox, Palette, StandardTableView , ScrollView} from "std-widgets.slint";
import { TableData , Relative} from "../types.slint";

export component Header inherits Rectangle {
    in-out property <bool> dark-mode;
    in-out property <string> title;
    y: 0px;
    height: 60px;
    background: Palette.color-scheme == ColorScheme.dark ? #2e3440 : #eceff4;

    HorizontalLayout {
        padding: 10px;
        alignment: space-between;
        Rectangle {
            Text {
                text: title;
                font-size: 24px;
                font-weight: 700;
                color: Palette.color-scheme == ColorScheme.dark ? #eceff4 : #2e3440;
            }
        }

        HorizontalLayout {
            spacing: 10px;
            alignment: end;
            Button {
                text: "Settings";
                height: 36px;
            }

            Button {
                text: "About";
                height: 36px;
            }
        }
    }
}

export component AddView inherits Rectangle {
    in-out property <Relative> relative;
    in-out property <string> name;
    border-radius: 10px;
    VerticalLayout {
        spacing: 10px;
        padding: 10px;

        Header {
            title: name;
        }

        ScrollView {
            VerticalLayout {
                spacing: 15px;
                GroupBox {
                    title: "Personal Information";
                    VerticalLayout {
                        spacing: 10px;
                        HorizontalBox {
                            spacing: 10px;
                            first-name := LineEdit {
                                placeholder-text: "First Name";
                            }

                            middle-name := LineEdit {
                                placeholder-text: "Middle Name";
                            }

                            last-name := LineEdit {
                                placeholder-text: "Last Name";
                            }
                        }

                        HorizontalBox {
                            spacing: 10px;
                            sex := LineEdit {
                                placeholder-text: "male or female";
                                width: 25%;
                            }

                            birthday := LineEdit {
                                placeholder-text: "Birthday (YYYY-MM-DD)";
                                width: 25%;
                            }

                            age := LineEdit {
                                placeholder-text: "Age (number)";
                                width: 15%;
                            }

                            phone := LineEdit {
                                placeholder-text: "Phone";
                                width: 25%;
                            }
                        }

                        HorizontalBox {
                            spacing: 10px;
                            email := LineEdit {
                                placeholder-text: "Email";
                                width: 40%;
                            }

                            LineEdit {
                                placeholder-text: "ATNum";
                                width: 25%;
                            }

                            sameness := LineEdit {
                                placeholder-text: "Sameness";
                                width: 25%;
                            }
                        }

                        HorizontalBox {
                            spacing: 10px;
                            lost := LineEdit {
                                placeholder-text: "Lost Reason";
                            }
                        }

                        HorizontalBox {
                            spacing: 10px;
                            pinned := CheckBox {
                                text: "Pinned";
                            }
                        }

                        HorizontalBox {
                            Button {
                                text: "Save";
                                clicked => {
                                    relative = {
                                        first-name: first-name.text,
                                        second-name: last-name.text,
                                        sex: sex.text,
                                        phone: phone.text,
                                        email: email.text,
                                        birthday: birthday.text,
                                        lost-reason: lost.text,
                                        sameness: sameness.text,
                                        pinned: pinned.checked
                                    };
                                    TableData.save-new-relative(relative)
                                }
                            }
                        }

                        HorizontalBox {
                            Rectangle {
                                height: 100px;
                                width: 100px;
                                border-radius: 5px;
                                background: Palette.color-scheme == ColorScheme.dark ? #4c566a : #d8dee9;
                                Text {
                                    text: "Image";
                                    color: Palette.color-scheme == ColorScheme.dark ? #eceff4 : #2e3440;
                                }
                            }

                            CustomButton {
                                title: "Upload Photo";
                                height: 30px;
                                background: Palette.color-scheme == ColorScheme.dark ? #5e81ac : #81a1c1;
                            }
                        }
                    }
                }

                GroupBox {
                    title: "Family Information";
                    VerticalLayout {
                        spacing: 10px;
                        HorizontalLayout {
                            alignment: space-around;
                            Button {
                                text: @tr("Add Mother");
                            }

                            Button {
                                text: @tr("Add Father");
                            }
                        }

                        HorizontalLayout {
                            spacing: 10px;
                            StandardTableView {
                                columns: [{ title: "Name" }, { title: "Born" }];
                                rows: [
                                    [{ text:"Sister Hotty" }, { text: "4-5-2023" }],
                                    [{ text: "Brother Bob Thorton" }, { text: "6-3-2024" }],
                                ];
                            }

                            StandardTableView {
                                columns: [{ title: "Name" }, { title: "Born" }];
                                rows: [
                                    [{ text:"Henrietta Hotty" }, { text: "4-5-2023" }],
                                    [{ text: "Billy Bob Thorton" }, { text: "6-3-2024" }],
                                ];
                            }
                        }

                        HorizontalLayout {
                            alignment: space-around;
                            Button {
                                text: @tr("Add Child");
                            }

                            Button {
                                text: @tr("Add Sibling");
                            }

                            Button {
                                text: @tr("Pin/Unpin record");
                            }

                            Button {
                                text: @tr("Save Record");
                                primary: true;
                            }

                            CustomButton {
                                title: @tr("Delete Record");
                                background: #bf616a;
                            }
                        }
                    }
                }
            }
        }
    }
}

  
// redundancy but it works lol
export component UpdateView inherits Rectangle {
    in-out property <Relative> relative;

    in-out property <string> name;
    border-radius: 10px;
    VerticalLayout {
        spacing: 10px;
        padding: 10px;

        Header {
            title: name;
        }

        ScrollView {
            VerticalLayout {
                spacing: 15px;
                GroupBox {
                    title: "Personal Information";
                    VerticalLayout {
                        spacing: 10px;
                        HorizontalBox {
                            spacing: 10px;
                            first-name := LineEdit {
                                placeholder-text: "First Name";
                            }

                            middle-name := LineEdit {
                                placeholder-text: "Middle Name";
                            }

                            last-name := LineEdit {
                                placeholder-text: "Last Name";
                            }
                        }

                        HorizontalBox {
                            spacing: 10px;
                            sex := LineEdit {
                                placeholder-text: "male or female";
                                width: 25%;
                            }

                            birthday := LineEdit {
                                placeholder-text: "Birthday (YYYY-MM-DD)";
                                width: 25%;
                            }

                            age := LineEdit {
                                placeholder-text: "Age (number)";
                                width: 15%;
                            }

                            phone := LineEdit {
                                placeholder-text: "Phone";
                                width: 25%;
                            }
                        }

                        HorizontalBox {
                            spacing: 10px;
                            email := LineEdit {
                                placeholder-text: "Email";
                                width: 40%;
                            }

                            LineEdit {
                                placeholder-text: "ATNum";
                                width: 25%;
                            }

                            sameness := LineEdit {
                                placeholder-text: "Sameness";
                                width: 25%;
                            }
                        }

                        HorizontalBox {
                            spacing: 10px;
                            lost := LineEdit {
                                placeholder-text: "Lost Reason";
                            }
                        }

                        HorizontalBox {
                            spacing: 10px;
                            pinned := CheckBox {
                                text: "Pinned";
                            }
                        }

                        HorizontalBox {
                            Button {
                                text: "Save";
                                clicked => {
                                    relative = {
                                        first-name: first-name.text,
                                        second-name: last-name.text,
                                        sex: sex.text,
                                        phone: phone.text,
                                        email: email.text,
                                        birthday: birthday.text,
                                        lost-reason: lost.text,
                                        sameness: sameness.text,
                                        pinned: pinned.checked
                                    };
                                    TableData.save-new-relative(relative)
                                }
                            }
                        }

                        HorizontalBox {
                            Rectangle {
                                height: 100px;
                                width: 100px;
                                border-radius: 5px;
                                background: Palette.color-scheme == ColorScheme.dark ? #4c566a : #d8dee9;
                                Text {
                                    text: "Image";
                                    color: Palette.color-scheme == ColorScheme.dark ? #eceff4 : #2e3440;
                                }
                            }

                            CustomButton {
                                title: "Upload Photo";
                                height: 30px;
                                background: Palette.color-scheme == ColorScheme.dark ? #5e81ac : #81a1c1;
                            }
                        }
                    }
                }

                GroupBox {
                    title: "Family Information";
                    VerticalLayout {
                        spacing: 10px;
                        HorizontalLayout {
                            alignment: space-around;
                            Button {
                                text: @tr("Add Mother");
                            }

                            Button {
                                text: @tr("Add Father");
                            }
                        }

                        HorizontalLayout {
                            spacing: 10px;
                            StandardTableView {
                                columns: [{ title: "Name" }, { title: "Born" }];
                                rows: [
                                    [{ text:"Sister Hotty" }, { text: "4-5-2023" }],
                                    [{ text: "Brother Bob Thorton" }, { text: "6-3-2024" }],
                                ];
                            }

                            StandardTableView {
                                columns: [{ title: "Name" }, { title: "Born" }];
                                rows: [
                                    [{ text:"Henrietta Hotty" }, { text: "4-5-2023" }],
                                    [{ text: "Billy Bob Thorton" }, { text: "6-3-2024" }],
                                ];
                            }
                        }

                        HorizontalLayout {
                            alignment: space-around;
                            Button {
                                text: @tr("Add Child");
                            }

                            Button {
                                text: @tr("Add Sibling");
                            }

                            Button {
                                text: @tr("Pin/Unpin record");
                            }

                            Button {
                                text: @tr("Save Record");
                                primary: true;
                            }

                            CustomButton {
                                title: @tr("Delete Record");
                                background: #bf616a;
                            }
                        }
                    }
                }
            }
        }
    }
}
