

import { TabWidget, VerticalBox, GroupBox, HorizontalBox, Button, CheckBox , StandardTableView} from "std-widgets.slint";
import { Tabs } from "../items/tabs.slint";
import { NotesSect } from "../items/notes-section.slint";

export component TabsView inherits Rectangle {
    preferred-height: 100%;
    preferred-width: 100%;
    callback show_popup_window();

    VerticalLayout {
        tabs := Rectangle {
            Tabs {
                show_popup_window => {
                    show_popup_window()
                }
            }
        }

        notes := Rectangle {
            max-height: 300px;
            NotesSect { }
        }
    }
}
