

import { TabWidget, VerticalBox, GroupBox, HorizontalBox, Button, CheckBox , StandardTableView} from "std-widgets.slint";
import { Tabs } from "../items/tabs.slint";
import { NotesSect } from "../items/notes-section.slint";

export component TabsView inherits Rectangle {
    min-width: 400px;
    preferred-height: 100%;
    preferred-width: 100%;

    VerticalLayout {
        tabs := Rectangle {
            Tabs { }
        }

        notes := Rectangle {
            max-height: 300px;
            NotesSect { }
        }
    }
}
