import {Palette,  Button, ScrollView, StandardTableView, TabWidget, VerticalBox } from "std-widgets.slint";
import { TableData } from "../types.slint";
import { CustomButton } from "../components/button.slint";
import { ListView } from "std-widgets.slint";
import { TaskBar } from "../components/TaskBar.slint";



component TableHeader inherits Rectangle {
    in property <string> column1;
    in property <string> column2;

    HorizontalLayout {
        alignment: space-around;
        Rectangle {
            Text {
                text: column1;
                font-size: 14px;
                font-weight: 700;
            }
        }

        Rectangle {
            if TableData.files_error != "" && !TableData.has_selected_row:Text {
                text: column2;
                font-size: 14px;
                font-weight: 700;
                color: red;
            }
        }
    }
}

export component NotesSect inherits Rectangle {
    property <string> active_note: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...";
    background: Palette.color-scheme == ColorScheme.dark ? #2e3440 : #eceff4;
    border-radius: 10px;
    callback open-note-popup();

    HorizontalLayout {
        padding: 16px;
        spacing: 16px;

        VerticalLayout {
            if TableData.has_selected_row: TaskBar {
                alignment: LayoutAlignment.end;
                h: 20px;
                Button {
                    text: "Edit";
                    height: 40px;
                    width: 140px;
                    clicked => {
                        TableData.show-update-window();
                    }
                }
            }

            Rectangle {
                width: 50%;
                TabWidget {
                    Tab {
                        title: "Files";
                        VerticalLayout {
                            spacing: 10px;
                            padding: 10px;

                            HorizontalLayout {
                                spacing: 10px;
                                Text {
                                    text: "Files";
                                    font-size: 20px;
                                    font-weight: 700;
                                    vertical-alignment: center;
                                }

                                CustomButton {
                                    visible: TableData.active-relative.id != "";
                                    title: "Add Files";
                                    height: 40px;
                                    width: 120px;
                                    background-color: #12d;
                                    clicked => {
                                        TableData.add-files-for-relative(TableData.current_row, TableData.active-relative.id);
                                    }
                                }
                            }

                            if TableData.files_error != "": TableHeader {
                                column2: TableData.files_error;
                            }

                            Rectangle {
                                border-color: #12d;
                                border-radius: 2px;
                                border-width: 2px;
                                padding: 40px;

                                ListView {
                                    for file in TableData.selected-relative-files: Rectangle {
                                        border-radius: 4px;
                                        border-width: 1px;
                                        border-color: #ddd;
                                        background: white;
                                        height: 35px;
                                        padding: 10px;
                                        HorizontalLayout {
                                            spacing: 8px;
                                            Text {
                                                text: file;
                                                font-size: 16px;
                                                color: #2c3e50;
                                                vertical-alignment: center;
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }

                    Tab {
                        title: "Notes";
                        VerticalLayout {
                            spacing: 10px;

                            HorizontalLayout {
                                spacing: 10px;
                                Text {
                                    text: "Notes";
                                    font-size: 20px;
                                    font-weight: 700;
                                    vertical-alignment: center;
                                }

                                CustomButton {
                                    visible: TableData.active-relative.id != "";
                                    height: 40px;
                                    width: 120px;
                                    title: "Add Note";
                                    background: #12d;
                                    clicked => {
                                        open-note-popup()
                                    }
                                }
                            }

                            if TableData.notes-error != "": TableHeader {
                                column2: TableData.notes-error;
                            }
                            Rectangle {
                                border-color: #12d;
                                border-radius: 2px;
                                border-width: 2px;
                                padding: 40px;

                                ListView {
                                    for note in TableData.selected-relative-notes: Rectangle {
                                        border-radius: 4px;
                                        border-width: 1px;
                                        border-color: #ddd;
                                        background: white;
                                        height: 35px;
                                        padding: 10px;
                                        HorizontalLayout {
                                            spacing: 8px;
                                            Text {
                                                text: note;
                                                font-size: 16px;
                                                color: #2c3e50;
                                                vertical-alignment: center;
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }

        VerticalLayout {
            width: 50%;
            spacing: 0px;
            header := Text {
                text: "Active Note";
                font-size: 24px;
                font-weight: 500;
                horizontal-alignment: center;
                color: Palette.color-scheme == ColorScheme.dark ? #e5e9f0 : #2e3440;
            }

            note-container := Rectangle {
                border-radius: 10px;
                background: Palette.color-scheme == ColorScheme.dark ? #3b4252 : #e5e9f0;
                VerticalBox {
                    padding: 16px;
                    text := Text {
                        width: 100%;
                        text: TableData.active-relative.note;
                        wrap: word-wrap;
                        font-size: 16px;
                        color: Palette.color-scheme == ColorScheme.dark ? #e5e9f0 : #2e3440;
                    }
                }
            }
        }
    }
}
