
import { TabWidget, StandardTableView, GroupBox, VerticalBox } from "std-widgets.slint";
import { Table, FemalesTable, EmployeesTable } from "../components/table.slint";
import { TableData , ActiveTab} from "../types.slint";
export component Tabs inherits Rectangle {
    callback show_popup_window();
    tab-widget := TabWidget {
        preferred-height: 100%;
        Tab {
            title: @tr("Relatives");

            VerticalBox {
                alignment: stretch;
                GroupBox {
                    vertical-stretch: 0;
                    Table {
                        data: TableData.relative;
                    }
                }
            }
        }

        Tab {
            title: @tr("Females");

            VerticalBox {
                alignment: stretch;
                GroupBox {
                    vertical-stretch: 0;
                    FemalesTable {
                        data: TableData.females;
                    }
                }
            }
        }

        Tab {
            title: "Employees";

            VerticalBox {
                alignment: stretch;
                GroupBox {
                    vertical-stretch: 0;
                    EmployeesTable {
                        data: TableData.employees;
                    }
                }
            }
        }
    }
}
