import { CustomButton } from "components/button.slint";
import {  AddView } from "views/add-view.slint";
import { UpdateView } from "views/update-view.slint";
import { TabsView } from "views/tabs-view.slint";
import { Palette, Button } from "std-widgets.slint";
import { TableData} from "types.slint";
import { Switch, TextEdit, HorizontalBox } from "std-widgets.slint";

export { TableData }

component Header inherits Rectangle {
    in-out property <bool> dark-mode;
    callback open-add-new();
    in-out property <string> title;
    height: 60px;
    background: Palette.color-scheme == ColorScheme.dark ? #2e3440 : #eceff4;

    HorizontalLayout {
        padding: 10px;
        alignment: space-between;
        Rectangle {
            Text {
                text: @tr("{}", title);
                font-size: 24px;
                font-weight: 700;
                color: Palette.color-scheme == ColorScheme.dark ? #eceff4 : #2e3440;
            }
        }

        @children
    }
}

export component Main inherits Window {
    min-width: 720px;
    min-height: 480px;
    title: "Genealogy App";
    HorizontalLayout {
        VerticalLayout {
            Header {
                title: "GenApp";
                HorizontalLayout {
                    spacing: 10px;
                    alignment: end;
                    Button {
                        text: "Add New";
                        height: 36px;
                        clicked => {
                            TableData.show-add-window()
                        }
                    }

                    Button {
                        text: "About";
                        height: 36px;
                    }

                    Switch {
                        text: @tr("Dark Mode");
                        checked: Palette.color-scheme == ColorScheme.dark;
                        toggled => {
                            Palette.color-scheme = self.checked ? ColorScheme.dark : ColorScheme.light;
                        }
                    }
                }
            }

            TabsView { }
        }
    }
}

export component UpdateWindow inherits Window {
    min-width: 720px;
    min-height: 480px;
    HorizontalLayout {

        VerticalLayout {
            Header {
                title: @tr("Update {}", TableData.active-relative.first-name);
                HorizontalLayout {
                    Switch {
                        text: @tr("Dark Mode");
                        checked: Palette.color-scheme == ColorScheme.dark;
                        toggled => {
                            Palette.color-scheme = self.checked ? ColorScheme.dark : ColorScheme.light;
                        }
                    }
                }
            }

            UpdateView { }
        }
    }
}

export component CreateWindow inherits Window {
    min-width: 650px;
    min-height: 430px;
    HorizontalLayout {

        VerticalLayout {
            Header {
                title: "Add New Relative";
                HorizontalLayout {
                    Switch {
                        text: @tr("Dark Mode");
                        checked: Palette.color-scheme == ColorScheme.dark;
                        toggled => {
                            Palette.color-scheme = self.checked ? ColorScheme.dark : ColorScheme.light;
                        }
                    }
                }
            }

            AddView { }
        }
    }
}
