
import { TabWidget, StandardTableView, GroupBox, VerticalBox } from "std-widgets.slint";
import { Table } from "../components/table.slint";
export component Tabs inherits Rectangle {
    TabWidget {
        preferred-height: 100%;
        Tab {
            title: @tr("Relatives");

            Text {
                y: 0;
                x: 20px;
                text: @tr("relatives");
            }

            VerticalBox {
                alignment: stretch;
                GroupBox {
                    vertical-stretch: 0;
                    Table { }
                }
            }
        }

        Tab {
            title: @tr("Females");

            Text {
                y: 0;
                x: 20px;
                text: @tr("Females");
            }

            VerticalBox {
                alignment: stretch;
                GroupBox {
                    vertical-stretch: 0;
                    Table { }
                }
            }
        }

        Tab {
            title: "Employees";

            Text {
                y: 0;
                x: 20px;
                text: @tr("Employees");
            }

            VerticalBox {
                alignment: stretch;
                GroupBox {
                    vertical-stretch: 0;
                    Table { }
                }
            }
        }
    }
}
