
import { TabWidget, StandardTableView, GroupBox, VerticalBox } from "std-widgets.slint";
import { Table, FemalesTable, EmployeesTable } from "../components/table.slint";
import { TableData , ActiveTab} from "../types.slint";
export component Tabs inherits Rectangle {

    callback show_popup_window();

    tab-widget := TabWidget {
        preferred-height: 100%;
        Tab {
            title: @tr("Relatives");
            Text {
                y: 0;
                x: 20px;
                text: @tr("relatives");
            }

            VerticalBox {
                alignment: stretch;
                GroupBox {
                    vertical-stretch: 0;
                    Table {
                        show-popup-window => {
                            TableData.active-tab = ActiveTab.relative;
                        }
                        data: TableData.relative;
                    }
                }
            }
        }

        Tab {
            title: @tr("Females");

            Text {
                y: 0;
                x: 20px;
                text: @tr("Females");
            }

            VerticalBox {
                alignment: stretch;
                GroupBox {
                    vertical-stretch: 0;
                    FemalesTable {
                        data: TableData.females;
                    }
                }
            }
        }

        Tab {
            title: "Employees";

            Text {
                y: 0;
                x: 20px;
                text: @tr("Employees");
            }

            VerticalBox {
                alignment: stretch;
                GroupBox {
                    vertical-stretch: 0;
                    EmployeesTable {
                        data: TableData.employees;
                    }
                }
            }
        }
    }
}
